# Generated by Django 3.2.5 on 2021-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('transport', models.IntegerField(verbose_name='Номер ТС')),
                ('time', models.TimeField(verbose_name='Время прибытия')),
                ('route', models.CharField(max_length=5, verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Маршрутный лист',
                'verbose_name_plural': 'Маршрутные листы',
            },
        ),
    ]
