# Generated by Django 3.2.5 on 2021-07-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=64, verbose_name='Марка, модель')),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('plate', models.CharField(max_length=16, verbose_name='Гос. рег. знак')),
            ],
        ),
    ]
