# Generated by Django 3.2.5 on 2021-07-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа расходов',
                'verbose_name_plural': 'Группы расходов',
            },
        ),
        migrations.CreateModel(
            name='InlineStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Инлайн',
                'verbose_name_plural': 'Инлайн',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_1', models.PositiveSmallIntegerField(verbose_name='Индекс')),
                ('num_2', models.PositiveSmallIntegerField(verbose_name='Подындекс')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('route_type', models.CharField(choices=[('Завоз', 'Завоз'), ('Вывоз', 'Вывоз')], default='Завоз', max_length=5, verbose_name='Тип поездки')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Остановка')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ п/п')),
                ('mark', models.CharField(max_length=64, verbose_name='Марка, модель')),
                ('year', models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='Год выпуска')),
                ('plate', models.CharField(max_length=16, verbose_name='Гос. рег. знак')),
            ],
            options={
                'verbose_name': 'Автотранспорт ГК "Альтекс"',
                'verbose_name_plural': 'Справочник автотранспорта ГК "Альтекс"',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='WHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('transport', models.PositiveSmallIntegerField(verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Заголовок маршрутного листа',
                'verbose_name_plural': 'Заголовки маршрутных листов',
            },
        ),
        migrations.CreateModel(
            name='WRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_id', models.PositiveIntegerField(verbose_name='№')),
                ('time_in', models.TimeField(verbose_name='Время при прибытии')),
                ('time_out', models.TimeField(verbose_name='Время при убытии')),
                ('route', models.CharField(max_length=5, verbose_name='Маршрут')),
                ('expense_group', models.CharField(max_length=32, verbose_name='Группа расходов')),
                ('unit', models.CharField(max_length=32, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Поездка маршрутного листа',
                'verbose_name_plural': 'Поездки маршрутных листов',
            },
        ),
        migrations.DeleteModel(
            name='WayBill',
        ),
        migrations.AddField(
            model_name='inlinestop',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.stop'),
        ),
        migrations.AddField(
            model_name='inlinestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.route'),
        ),
    ]
