# Generated by Django 3.2.5 on 2021-07-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_transport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Автотранспорт ГК "Альтекс"', 'verbose_name_plural': 'Справочник автотранспорта ГК "Альтекс"'},
        ),
    ]
