# Generated by Django 3.2.5 on 2021-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_transport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False, verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='Год выпуска'),
        ),
    ]
