# Generated by Django 3.2.6 on 2021-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20210803_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('Завоз', 'Завоз'), ('Вывоз', 'Вывоз')], default='Завоз', max_length=5, verbose_name='Тип поездки'),
        ),
    ]
