# Generated by Django 3.2.5 on 2021-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20210705_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transport',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Номер ТС'),
        ),
    ]
