# Generated by Django 3.2.5 on 2021-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_waybill_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transport',
            field=models.DecimalField(choices=[], decimal_places=0, max_digits=3, verbose_name='Номер ТС'),
        ),
    ]
