# Generated by Django 3.2.5 on 2021-07-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_waybill_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.transport'),
        ),
    ]
