# Generated by Django 3.2.5 on 2021-07-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_transport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='№ п/п'),
        ),
    ]
