# Generated by Django 3.2.5 on 2021-07-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_rename_waybill_waybillride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waybillride',
            options={'verbose_name': 'Поездка маршрутного листа', 'verbose_name_plural': 'Поездки маршрутных листов'},
        ),
        migrations.CreateModel(
            name='WayBillHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.transport')),
            ],
            options={
                'verbose_name': 'Заголовок маршрутного листа',
                'verbose_name_plural': 'Заголовки маршрутных листов',
            },
        ),
    ]
