# Generated by Django 3.2.5 on 2021-07-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_auto_20210707_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WayBillHead',
            new_name='WHead',
        ),
        migrations.RenameModel(
            old_name='WayBillRide',
            new_name='WRide',
        ),
    ]
