# Generated by Django 3.2.5 on 2021-07-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_wride_ride_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wride',
            old_name='ride_id',
            new_name='head_id',
        ),
    ]
