# Generated by Django 3.2.5 on 2021-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_whead_creation_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Остановка')),
            ],
            options={
                'verbose_name': 'Остановка',
            },
        ),
        migrations.AlterField(
            model_name='wride',
            name='time_in',
            field=models.TimeField(verbose_name='Время при прибытии'),
        ),
        migrations.AlterField(
            model_name='wride',
            name='time_out',
            field=models.TimeField(verbose_name='Время при убытии'),
        ),
    ]
