# Generated by Django 3.2.5 on 2021-07-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_auto_20210712_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
