# Generated by Django 3.2.5 on 2021-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0019_auto_20210713_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
