# Generated by Django 3.2.5 on 2021-07-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0022_auto_20210714_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='num',
        ),
        migrations.AddField(
            model_name='route',
            name='num_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='num_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Подындекс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inlinestop',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_main.stop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inlinestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.route'),
        ),
        migrations.AlterField(
            model_name='inlinestop',
            name='time',
            field=models.TimeField(blank=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('Вывоз', 'Вывоз'), ('Завоз', 'Завоз')], default='Завоз', max_length=5, verbose_name='Тип поездки'),
        ),
    ]
