# Generated by Django 3.2.5 on 2021-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0023_auto_20210714_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='num_1',
        ),
        migrations.RemoveField(
            model_name='route',
            name='num_2',
        ),
        migrations.AddField(
            model_name='route',
            name='num',
            field=models.CharField(default=0, max_length=5, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
