# Generated by Django 3.2.5 on 2021-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0024_auto_20210714_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='num',
        ),
        migrations.AddField(
            model_name='route',
            name='num_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='num_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Подындекс'),
            preserve_default=False,
        ),
    ]
