# Generated by Django 3.2.5 on 2021-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0030_alter_route_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinestop',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='whead',
            name='transport',
            field=models.PositiveSmallIntegerField(verbose_name='Транспорт'),
        ),
    ]
