# Generated by Django 3.2.5 on 2021-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0032_auto_20210715_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('Завоз', 'Завоз'), ('Вывоз', 'Вывоз')], default='Завоз', max_length=5, verbose_name='Тип поездки'),
        ),
    ]
