# Generated by Django 3.2.5 on 2021-07-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0033_alter_route_route_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlinestop',
            options={'verbose_name': 'Инлайн', 'verbose_name_plural': 'Инлайн'},
        ),
    ]
